#Create one replica of application basically creating one pod using image that already in my DockerHub kiranpayyavuala/mykubeimages:v1
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: kiranpayyavuala/mykubeimages:v1
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080
